apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: zone-devyatkino-ippool
spec:
  cidr: 10.244.102.1/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: zone == "devyatkino"

---
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: zone-okhta-ippool 
spec:
  cidr: 10.244.102.2/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: zone == "okhta"
  
